FROM ubuntu:24.04
 
ENV DEBIAN_FRONTEND=noninteractive
ENV NGINX_VERSION=1.22.1
ENV PCRE_VERSION=8.45
ENV ZLIB_VERSION=1.2.13
ENV OPENSSL_VERSION=3.4.0
 
RUN apt-get update && apt-get install -y \
    apache2-dev apache2-utils autoconf automake build-essential \
    geoip-bin geoip-database git \
    libcurl4-openssl-dev libgd-dev libgeoip-dev libgeos++-dev \
    libpcre3 libpcre3-dev libssl-dev libtool \
    libxml2-dev libxslt-dev pkgconf \
    wget ca-certificates curl \
    && rm -rf /var/lib/apt/lists/*
 
RUN groupadd -r nginx && \
    useradd -r -g nginx -s /sbin/nologin -M nginx
 
WORKDIR /opt
 
RUN git clone -b nginx_refactoring https://github.com/SpiderLabs/ModSecurity.git && \
    cd ModSecurity && \
    ./autogen.sh && \
    ./configure --enable-standalone-module --disable-mlogc && \
    make
 
RUN git clone https://github.com/AirisX/nginx_cookie_flag_module.git && \
    cd nginx_cookie_flag_module && \
    git submodule init && \
    git submodule update
 
RUN git clone https://github.com/eustas/ngx_brotli.git && \
    cd ngx_brotli && \
    git submodule update --init
 
RUN curl -fL http://nginx.org/download/nginx-${NGINX_VERSION}.tar.gz -o nginx.tar.gz && \
    curl -fL https://sourceforge.net/projects/pcre/files/pcre/${PCRE_VERSION}/pcre-${PCRE_VERSION}.tar.gz/download -o pcre.tar.gz && \
    curl -fL https://zlib.net/fossils/zlib-${ZLIB_VERSION}.tar.gz -o zlib.tar.gz && \
    curl -fL https://www.openssl.org/source/openssl-${OPENSSL_VERSION}.tar.gz -o openssl.tar.gz && \
    tar xzf nginx.tar.gz && \
    tar xzf pcre.tar.gz && \
    tar xzf zlib.tar.gz && \
    tar xzf openssl.tar.gz && \
    rm *.tar.gz
 
WORKDIR /opt/nginx-${NGINX_VERSION}
 
RUN ./configure \
    --prefix=/etc/nginx \
    --sbin-path=/usr/sbin/nginx \
    --modules-path=/usr/lib/nginx/modules \
    --conf-path=/etc/nginx/nginx.conf \
    --error-log-path=/var/log/nginx/error.log \
    --pid-path=/var/run/nginx.pid \
    --lock-path=/var/run/nginx.lock \
    --user=nginx \
    --group=nginx \
    --with-threads \
    --with-file-aio \
    --with-http_ssl_module \
    --with-http_v2_module \
    --with-http_realip_module \
    --with-http_gzip_static_module \
    --with-http_stub_status_module \
    --with-stream \
    --with-stream_ssl_module \
    --with-compat \
    --with-pcre=../pcre-${PCRE_VERSION} \
    --with-zlib=../zlib-${ZLIB_VERSION} \
    --with-openssl=../openssl-${OPENSSL_VERSION} \
    --with-openssl-opt=no-nextprotoneg \
    --with-debug \
    --with-cc-opt="-Wno-error=address -Wno-error=deprecated-declarations" \
    --add-module=/opt/nginx_cookie_flag_module \
    --add-module=/opt/ngx_brotli \
    --add-module=/opt/ModSecurity/nginx/modsecurity \
&& make \
&& make install
 
RUN mkdir -p /var/cache/nginx/client_temp && \
    mkdir -p /var/log/nginx && \
    chown -R nginx:nginx /var/cache/nginx /var/log/nginx
 
EXPOSE 80 443
 
COPY nginx.conf /etc/nginx/nginx.conf
RUN mkdir -p /var/www/html && chown -R nginx:nginx /var/www/html
 
CMD ["nginx", "-g", "daemon off;"]
