services:
  backend:
    build:
      context: ./backend
    network_mode: "host"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://127.0.0.1:3306/vconnect_prod_portal?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: devdb
      SPRING_DATASOURCE_PASSWORD: ""
      JWT_SECRET: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      PORTAL_DB: vconnect_prod_portal
      CATALOG_DB: vconnect_prod_catalog
      VCONNECT_DB: vconnect
      CLIENT_PASS_SALT: 38fc4120