server:
  port: 8080

spring:
  application:
    name: wejoinlife-api

  threads:
    virtual:
      enabled: true

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://127.0.0.1:3306/vconnect_prod_portal?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true}
    username: ${SPRING_DATASOURCE_USERNAME:devdb}
    password: ${SPRING_DATASOURCE_PASSWORD:}
    driver-class-name: com.mysql.cj.jdbc.Driver

  sql:
    init:
      mode: never # Disabled: will use existing database

application:
  security:
    jwt:
      secret-key: ${JWT_SECRET:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}
      expiration: 86400000

  database:
    portal-db: ${PORTAL_DB:vconnect_prod_portal}

  cart:
    cookie-name: ${CART_COOKIE_NAME:vconnect_cart}
